export const CAPABILITIES = Object.freeze({
  READ: "read",
  FLAG: "flag",
  COMMENT: "comment",
  MANAGE_REVIEWS: "manage_reviews",
  MANAGE_DOCUMENTS: "manage_documents",
  PUBLISH: "publish",
  ADMINISTER: "administer"
});

export const CAPABILITY_GRANTS = Object.freeze({
  public: new Set([CAPABILITIES.READ, CAPABILITIES.FLAG, CAPABILITIES.COMMENT]),
  moderator: new Set([CAPABILITIES.READ, CAPABILITIES.FLAG, CAPABILITIES.COMMENT]),
  developer: new Set([CAPABILITIES.READ, CAPABILITIES.FLAG, CAPABILITIES.COMMENT, CAPABILITIES.MANAGE_REVIEWS, CAPABILITIES.MANAGE_DOCUMENTS, CAPABILITIES.PUBLISH]),
  administrator: new Set([CAPABILITIES.READ, CAPABILITIES.FLAG, CAPABILITIES.COMMENT, CAPABILITIES.MANAGE_REVIEWS, CAPABILITIES.MANAGE_DOCUMENTS, CAPABILITIES.PUBLISH, CAPABILITIES.ADMINISTER])
});

export function hasCapability(identity, capability) {
  return CAPABILITY_GRANTS[identity]?.has(capability) ?? false;
}
